version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    restart: no

  brawlstars-etl:
    build: ./etl_service
    container_name: brawlstars-etl-container
    environment:
      - BRAWLSTARS_API_KEY=${BRAWLSTARS_API_KEY}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DB=${MYSQL_DB}
    depends_on:
      - mysql
    restart: no

  brawlstars-web-ui:
    build: ./web_ui_service
    container_name: brawlstars-web-ui-container
    ports:
      - "5000:5000"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DB=${MYSQL_DB}
    depends_on:
      brawlstars-etl:
        condition: service_completed_successfully
      mysql:
        condition: service_started