country_codes:
  - US
  - CA
  - BR
  - GB
  - DE
  - FR
  - IT
  - ES
  - JP
  - KR
  - CN
  - AU
  - IN
  - TR
  - RU
  - SE
  - NO
  - FI
  - DK
  - MX
  - AR
  - CL
  - ZA
  - SG
  - MY
  - PH
  - ID
  - TH
  - global